### ISSUE TITLE
⭐ Support StableLM From StabilityAI

### ISSUE THREAD

**Issue by MarkSchmidty** [oobabooga/text-generation-webui#1383]
[Blog Post Announcement](https://stability.ai/blog/stability-ai-launches-the-first-of-its-stablelm-suite-of-language-models)
(It may be using the same architecture as GPT-NeoX)

[![Launch In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Stability-AI/StableLM/blob/main/notebooks/stablelm-alpha.ipynb) 

[GitHub Repo](https://github.com/Stability-AI/StableLM)

In case these links 404 due to being posted early by accident:
https://archive.is/ZQszO
https://archive.ph/U0Pr8

(Checkpoint links are Hugging Face repos with model weights)
| Size | StableLM-Base-Alpha                        | StableLM-Tuned-Alpha                      | Training Tokens | Context Window | Web Demo |
|----------------|-------------------------------|-----------------------------|----------|----------|----------|
|3B| [checkpoint](https://huggingface.co/stabilityai/stablelm-base-alpha-3b/) |[checkpoint](https://huggingface.co/stabilityai/stablelm-tuned-alpha-3b/)            | 800B | 4096 | |
|7B| [checkpoint](https://huggingface.co/stabilityai/stablelm-base-alpha-7b) |[checkpoint](https://huggingface.co/stabilityai/stablelm-tuned-alpha-7b)            | 800B | 4096 | [HuggingFace](https://huggingface.co/spaces/stabilityai/stablelm-tuned-alpha-chat) |
|15B| (in progress) | (pending) | 1.5T | | |
|30B| (in progress) | (pending) | 1.5T | | |
|65B| (in progress) | (pending) | 1.5T | | |
|175B| (planned) | | | | |

**Comment by underwaterbepis** [comment]
Seems to work fine for me as is

**Comment by Ph0rk0z** [comment]
Just have to set the longer contexts.. these are GPT-J or NeoX as far as I know.

**Comment by eiery** [comment]
The 3B base model works out of the box for me on oobabooga but the quality of the generated text is visibly worse than the 3B Pythia and Pygmalion. It's not really coherent and likes to go off-topic.

**Comment by CarlKenner** [comment]
> Seems to work fine for me as is

Then please provide the steps you used to make it work.

**Comment by MarkSchmidty** [comment]
Put it in a folder next to the rest of your models and then select it from the dropdown. 
![image](https://user-images.githubusercontent.com/5949853/233243705-feb1581b-612e-446c-8cfc-d67ecc74fdc7.png)

Note that the "Tuned" versions need to be prompted like:
```
<|SYSTEM|>
(Describe the AI chatbot here)
<|USER|>
(Place your message here)
<|ASSISTANT|>
(Response will come here)
```

**Comment by nmrugg** [comment]
> Note that the "Tuned" versions need to be prompted like:
> 
> ```
> <|SYSTEM|>
> (Describe the AI chatbot here)
> <|USER|>
> (Place your message here)
> <|ASSISTANT|>
> (Response will come here)
> ```

Sorry for the newbie question, but could someone explain how to do that?

**Comment by minipasila** [comment]
> > Note that the "Tuned" versions need to be prompted like:
> > ```
> > <|SYSTEM|>
> > (Describe the AI chatbot here)
> > <|USER|>
> > (Place your message here)
> > <|ASSISTANT|>
> > (Response will come here)
> > ```
> 
> Sorry for the newbie question, but could someone explain how to do that?

I think you just add <|SYSTEM|> before any character description and then name the bot <|ASSISTANT|> and then You as <|USER|>. When you use the cai-chat/chat.
There's also an instruct mode in --chat but you'll have to make a new file like this:
```
name: "<|ASSISTANT|>"
your_name: "<|USER|>"
context: "<|SYSTEM|>"
```
and name it something like StableLM.yaml inside the \characters\instruction-following\ folder.

**Comment by CarlKenner** [comment]
I added support for this in my pull request #1395.
Let me know if there's anything else we need to do besides what's in my pull request.

**Comment by Ph0rk0z** [comment]
The 4096 context does indeed work. The model is incredibly dumb. I think it needs to be quantized to run at full context in 24gb.

**Comment by MarkSchmidty** [comment]
> I think it needs to be quantized to run at full context in 24gb.

There are some 16bit versions here:  
[huggingface.co/vvsotnikov/stablelm-tuned-alpha-7b-16bit](https://huggingface.co/vvsotnikov/stablelm-tuned-alpha-7b-16bit)  
[huggingface.co/vvsotnikov/stablelm-tuned-alpha-3b-16bit](https://huggingface.co/vvsotnikov/stablelm-tuned-alpha-3b-16bit)  
  
Note that because it's GPT-NeoX based, GPT-NeoX GPTQ 4bit quantization is possible with existing GPT-NeoX libraries.

**Comment by Ph0rk0z** [comment]
So the weights they released were FP32? This must be why I OOM after 3k context. I am checking my 4bit neox right now and oh boy is the perplexity not great.

**Comment by MarkSchmidty** [comment]
Yes the quality / benchmarks are currently not good, to say the least. I would hold out for the next training checkpoint tbh.

**Comment by Ph0rk0z** [comment]
They will be worse in 4bit judging by how pythia and lotus turned out converted to GPTQ. I guess I have to find a script to convert my FP32 base model to FP16.

**Comment by CarlKenner** [comment]
Yeah, the quality of this model isn't great. But I don't think that's our fault (if you're using my pull request). I added presets so you can run the model with the same parameters as on their website, if you want to verify whether we have implemented it correctly.

One thing my pull request doesn't do yet is handle all the different stopping tokens that StableLM uses.

**Comment by MarkSchmidty** [comment]
It's definitely not your PR's fault. See https://github.com/Stability-AI/StableLM/issues/30

**Comment by mcmonkey4eva** [comment]
As noted in that thread, adding `Question: ` and `User: ` may improve quality of results on the Alpha.
(It's still not going to be great, but a little better)
