### ISSUE TITLE
Can't use Llama-2-70b-chat

### ISSUE THREAD

**Issue by iibw** [oobabooga/text-generation-webui#3201]
### Describe the bug

Llama-2-7b-chat and Llama-2-13b-chat work perfectly, but no matter how I load Llama-2-70b-chat, I get the same error when trying to generate text. I'm able to run the original llama-65b with no problem either. I downloaded the models from Meta's servers and converted them to the HF format (via the instructions provided in this repo) myself.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Download the Llama-2-70b-chat model weights from Meta
2. Convert Llama-2-70b-chat to the HF format with https://github.com/oobabooga/text-generation-webui/blob/main/docs/LLaMA-v2-model.md
3. Load the model with text-generation-webui
4. Try to generate some text and it will error out

### Logs

```shell
Traceback (most recent call last):
  File "/home/default/text-generation-webui/modules/callbacks.py", line 55, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "/home/default/text-generation-webui/modules/text_generation.py", line 297, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/default/anaconda3/envs/textgen2/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/default/anaconda3/envs/textgen2/lib/python3.10/site-packages/transformers/generation/utils.py", line 1572, in generate
    return self.sample(
  File "/home/default/anaconda3/envs/textgen2/lib/python3.10/site-packages/transformers/generation/utils.py", line 2619, in sample
    outputs = self(
  File "/home/default/anaconda3/envs/textgen2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/default/anaconda3/envs/textgen2/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/default/anaconda3/envs/textgen2/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 688, in forward
    outputs = self.model(
  File "/home/default/anaconda3/envs/textgen2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/default/anaconda3/envs/textgen2/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 578, in forward
    layer_outputs = decoder_layer(
  File "/home/default/anaconda3/envs/textgen2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/default/anaconda3/envs/textgen2/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/default/anaconda3/envs/textgen2/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 292, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/default/anaconda3/envs/textgen2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/default/anaconda3/envs/textgen2/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/default/anaconda3/envs/textgen2/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 195, in forward
    key_states = self.k_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
RuntimeError: shape '[1, 31, 64, 128]' is invalid for input of size 31744
```

### System Info

```shell
- Python 3.10.9
- Fresh install of text-generation-webui
- No errors on installation
```

**Comment by iibw** [comment]
Figured it out. The version of transformers is out of date and needs to be added to the `requirements.txt`.

Executing `pip install transformers --upgrade` will update it to the latest version if anyone is reading this and has already installed everything.

I'll leave this issue open until the changes are made to the `requirements.txt`.

**Comment by neuhaus** [comment]
@iibw Very helpful, thanks.

**Comment by LagPixelLOL** [comment]
After updating transformers, the error message is gone, but the model doesn't generate anything.
I'm using llama 2 70b gptq loaded with AutoGPTQ.

**Comment by iibw** [comment]
@LagPixelLOL I haven't tested the GPTQ version of 70b so maybe there's incompatibility with AutoGPTQ and the latest version of transformers?

**Comment by LagPixelLOL** [comment]
> @LagPixelLOL I haven't tested the GPTQ version of 70b so maybe there's incompatibility with AutoGPTQ and the latest version of transformers?

IDK, but 13B version is working for me.

**Comment by iibw** [comment]
Gotcha, well, I can't speak to the other models, GPTQ, or GGML, but 70b-chat with the Transformers HF loader works for me with a fresh install and `pip install transformers --upgrade`.

**Comment by LagPixelLOL** [comment]
I don't want to download 130GB :'(

**Comment by iibw** [comment]
As of https://github.com/oobabooga/text-generation-webui/commit/08c23b62c7a5dde28842c9029465fdfd6435f2fd, my bug has been resolved

**Comment by RageshAntony** [comment]
@Panchovix 

Does this commit work directly in text-gen-web-ui ? how to update ?

**Comment by Ph0rk0z** [comment]
If you're on windows you have to get new wheels. For me on linux I just go into the repositories/exllama folder and do a git pull. It re-compiles the kernel and off I go.

**Comment by wholehope** [comment]
Mine still does not work for Llama-2-70b, but Llama-2-13b and 7b works. text-generation-webui and exllama are on the latest as of Jul-22.

**Comment by Ph0rk0z** [comment]
Definitely works for me.. and now with the guanaco lora if you disable fused attention.

**Comment by RageshAntony** [comment]
@wholehope 

Are you using runpod template . Then create new pod again. template fixed and updated by author

**Comment by wholehope** [comment]
Yep, I was using runpod. With a new pod, the problem is resolved. Thank you so much.
