### ISSUE TITLE
DLL cannot be loaded while importing exllamav2_ext

### ISSUE THREAD

**Issue by DiamondGlassDrill** [oobabooga/text-generation-webui#4217]
### Describe the bug

Loading of exllamav2 is broken and throws error see below

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Traceback (most recent call last):
  File "...\text-generation-webui\server.py", line 222, in <module>
    shared.model, shared.tokenizer = load_model(model_name)
  File "...\text-generation-webui\modules\models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
  File "...\text-generation-webui\modules\models.py", line 337, in ExLlamav2_loader
    from modules.exllamav2 import Exllamav2Model
  File "...\text-generation-webui\modules\exllamav2.py", line 5, in <module>
    from exllamav2 import (
  File "...\text-generation-webui\installer_files\env\lib\site-packages\exllamav2\__init__.py", line 3, in <module>
    from exllamav2.model import ExLlamaV2
  File "...\text-generation-webui\installer_files\env\lib\site-packages\exllamav2\model.py", line 12, in <module>
    from exllamav2.linear import ExLlamaV2Linear
  File "...\text-generation-webui\installer_files\env\lib\site-packages\exllamav2\linear.py", line 5, in <module>
    from exllamav2 import ext
  File "...\text-generation-webui\installer_files\env\lib\site-packages\exllamav2\ext.py", line 14, in <module>
    import exllamav2_ext

ImportError: DLL load failed while importing exllamav2_ext: The specified procedure could not be found.
Press any key . . .

### Logs

```shell
See above
```

### System Info

```shell
W11 / rtx 3090 / Cuda 11.8
```

**Comment by Compstudent** [comment]
have same bug

**Comment by Menthols426** [comment]
Same, broke as soon as I updated earlier. Any fixes?

**Comment by hongyanca** [comment]
I had the same error.

What worked for me:
1. Since commit d33facc bumped PyTorch version to 11.8, I manually reinstalled PyTorch 11.8 using instructions from https://pytorch.org/get-started/locally/, specifically `conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia` under `cmd_windows.bat`
2. Upgrade pip packages: `pip install -r requirements.txt --upgrade`
3. It seems package `cchardet` is missing, so I installed it: `pip install cchardet`

**Comment by DiamondGlassDrill** [comment]
Solved with newest ooba version! It automatically downgraded everything to 11.7

**Comment by DiamondGlassDrill** [comment]
**Better way. Upgrade to torch 2.1:**

1. In ooba env (CMD) pip install torch==2.1 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
2. Then update ooba again ;) Done!

**Comment by kerbi** [comment]
Did what @DiamondGlassDrill suggested,

> **Better way. Upgrade to torch 2.1:**
> 
>     1. In ooba env (CMD) pip install torch==2.1 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
> 
>     2. Then update ooba again ;) Done!

had an error with xformers.

To fix the issue with transformers not being okay with torch 2.1, i uninstalled it and did : pip install --pre xformers
https://github.com/facebookresearch/xformers/issues/870#issuecomment-1750180582

**Comment by ParisNeo** [comment]
the error is back:
ImportError: DLL load failed while importing exllamav2_ext

**Comment by jfan3** [comment]
Same error for me. nvcc 12.3, gcc 5.3.0

**Comment by rinukkusu** [comment]
Same for me and I just upgraded from an install from 2023-06 that was working until now 😢

**Comment by ParisNeo** [comment]
I really don't understand where does it come from.
It looks like it hapens when exllamav2_ext is being imported. Maybe I need to ask in exllamav2 repo

**Comment by rinukkusu** [comment]
It was fixed for me, when I did a clean install from the 2024-01-28 snapshot.

**Comment by biship** [comment]
The exllamav2 build needs to match the version of torch installed.

So fo an older version of exllamav2 , which is built on torch 2.1.2:
From https://github.com/turboderp/exllamav2/releases/tag/v0.0.12
pip install exllamav2-0.0.12+cu121-cp311-cp311-win_amd64.whl
pip install torch==2.1.2 --index-url https://download.pytorch.org/whl/cu121
pip install torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cu121
pip install torchvision==0.16.2 --index-url https://download.pytorch.org/whl/cu121

Or for the latest version, which is built on torch 2.20:
From https://github.com/turboderp/exllamav2/releases/tag/v0.0.13
pip install exllamav2-0.0.13+cu121-cp311-cp311-win_amd64.whl
pip install torch==2.2.0 --index-url https://download.pytorch.org/whl/cu121 --upgrade
pip install torchaudio==2.2.0 --index-url https://download.pytorch.org/whl/cu121 --upgrade
pip install torchvision==0.17.0 --index-url https://download.pytorch.org/whl/cu121 --upgrade

Or, as as of today, the latest wheel is 2.20, so you can just use:
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 --upgrade

**Comment by ParisNeo** [comment]
I found the problem on my side. It was the cuda version that was not matching the exllamav2 wheel I was using.
Now it is working like charm and lollms users can enjoy fast smooth text generation.

**Comment by Jimmyliuii** [comment]
> I found the problem on my side. It was the cuda version that was not matching the exllamav2 wheel I was using. Now it is working like charm and lollms users can enjoy fast smooth text generation.

Could you please tell me what the fix is?
I am now in 
`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Feb__8_05:53:42_Coordinated_Universal_Time_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0`

`torch                         2.2.0+cu121
torch-audiomentations         0.11.0
torch-pitch-shift             1.2.4
torchaudio                    2.2.0+cu121
torchmetrics                  1.3.0.post0
torchvision                   0.17.0+cu121`

I am still encountering `ImportError: DLL load failed while importing exllamav2_ext:` 
I tried reinstall package,

**Comment by HR-04** [comment]
To solve this 

I used 

exllamav2 - 0.1.4+cu121.torch2.2.0 - Download_Link : pip install https://github.com/turboderp/exllamav2/releases/download/v0.1.4/exllamav2-0.1.4%2Bcu121.torch2.2.0-cp310-cp310-win_amd64.whl

link : https://github.com/turboderp/exllamav2/releases

with Torch version

torch    2.2.0+cu121 - Download_Link : pip install torch==2.2.0 --index-url https://download.pytorch.org/whl/cu121 --upgrade

torchaudio     2.2.0+cu121 - Download_Link : pip install torchaudio==2.2.0 --index-url https://download.pytorch.org/whl/cu121 --upgrade

torchvision     0.17.0+cu121 - Download_Link : pip install torchvision==0.17.0 --index-url https://download.pytorch.org/whl/cu121 --upgrade

also do check llama_cpp version

llama_cpp_python                  0.2.38+cpuavx2
llama_cpp_python_cuda             0.2.38+cu121
llama_cpp_python_cuda_tensorcores  0.2.38+cu121


with these versions the error got solved for me.
