### ISSUE TITLE
Install.bat not running

### ISSUE THREAD

**Issue by AbslanX** [oobabooga/text-generation-webui#944]
### Describe the bug

Installer fails with this error : 

critical libmamba Download error (28) Timeout was reached [https://binstar-cio-packages-prod.s3.amazonaws.com/62eaaa07c]    SSL/TLS connection timeout

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

download the installer

unzip

run install.bat

### Logs

```shell
WARNING: This script relies on Micromamba which may have issues on some systems when installed under a path with spaces.         May also have issues with long paths.

What is your GPU?

A) NVIDIA
B) None (I want to run in CPU mode)

Input> a
"Downloading Micromamba from https://github.com/mamba-org/micromamba-releases/releases/download/1.4.0-0/micromamba-win-64 to E:\OogoBooga\oobabooga-windows\installer_files\mamba\micromamba.exe"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
100 8220k  100 8220k    0     0  1249k      0  0:00:06  0:00:06 --:--:-- 9441k
Micromamba version:
1.4.0
Packages to install: python=3.10.9 pytorch[version=2,build=py3.10_cuda11.7*] torchvision torchaudio pytorch-cuda=11.7 cuda-toolkit ninja git

                                           __
          __  ______ ___  ____ _____ ___  / /_  ____ _
         / / / / __ `__ \/ __ `/ __ `__ \/ __ \/ __ `/
        / /_/ / / / / / / /_/ / / / / / / /_/ / /_/ /
       / .___/_/ /_/ /_/\__,_/_/ /_/ /_/_.___/\__,_/
      /_/

pytorch/noarch                                      10.0kB @   1.3kB/s  7.7s
nvidia/win-64                                       89.0kB @  11.6kB/s  7.7s
pytorch/win-64                                     119.6kB @  15.5kB/s  7.7s
nvidia/noarch                                        2.8kB @ 355.0 B/s  0.0s
nvidia/label/cuda-11.7.0/win-64                      5.4kB @ 693.0 B/s  7.8s
nvidia/label/cuda-11.7.0/noarch                    130.0 B @  16.0 B/s  7.8s
conda-forge/noarch                                  11.8MB @   1.2MB/s  2.8s
conda-forge/win-64                                  19.8MB @   1.6MB/s  5.2s

Transaction

  Prefix: E:\OogoBooga\oobabooga-windows\installer_files\env

  Updating specs:

   - python=3.10.9
   - pytorch==2[build=py3.10_cuda11.7*]
   - torchvision
   - torchaudio
   - pytorch-cuda=11.7
   - cuda-toolkit
   - ninja
   - git


  Package                               Version  Build                     Channel                              Size
----------------------------------------------------------------------------------------------------------------------
  Install:
----------------------------------------------------------------------------------------------------------------------

  + blas                                  2.116  mkl                       conda-forge/win-64                   14kB
  + blas-devel                            3.9.0  16_win64_mkl              conda-forge/win-64                   13kB
  + brotlipy                              0.7.0  py310h8d17308_1005        conda-forge/win-64                  340kB
  + bzip2                                 1.0.8  h8ffe710_4                conda-forge/win-64                  152kB
  + ca-certificates                   2022.12.7  h5b45459_0                conda-forge/win-64                  147kB
  + certifi                           2022.12.7  pyhd8ed1ab_0              conda-forge/noarch                  151kB
  + cffi                                 1.15.1  py310h628cb3f_3           conda-forge/win-64                  234kB
  + charset-normalizer                    3.1.0  pyhd8ed1ab_0              conda-forge/noarch                   45kB
  + cryptography                         40.0.1  py310h6e82f81_0           conda-forge/win-64                    1MB
  + cuda-cccl                           11.7.58  0                         nvidia/label/cuda-11.7.0/win-64       1MB
  + cuda-command-line-tools              11.7.0  0                         nvidia/label/cuda-11.7.0/win-64       1kB
  + cuda-compiler                        11.7.0  0                         nvidia/label/cuda-11.7.0/win-64       1kB
  + cuda-cudart                         11.7.60  0                         nvidia/label/cuda-11.7.0/win-64       1MB
  + cuda-cudart-dev                     11.7.60  0                         nvidia/label/cuda-11.7.0/win-64     712kB
  + cuda-cuobjdump                      11.7.50  0                         nvidia/label/cuda-11.7.0/win-64       3MB
  + cuda-cupti                          11.7.50  0                         nvidia/label/cuda-11.7.0/win-64      11MB
  + cuda-cuxxfilt                       11.7.50  0                         nvidia/label/cuda-11.7.0/win-64     169kB
  + cuda-documentation                  11.7.50  0                         nvidia/label/cuda-11.7.0/win-64      93kB
  + cuda-libraries                       11.7.0  0                         nvidia/label/cuda-11.7.0/win-64       1kB
  + cuda-libraries-dev                   11.7.0  0                         nvidia/label/cuda-11.7.0/win-64       1kB
  + cuda-memcheck                       11.7.50  0                         nvidia/label/cuda-11.7.0/win-64     187kB
  + cuda-nsight-compute                  11.7.0  0                         nvidia/label/cuda-11.7.0/win-64       1kB
  + cuda-nvcc                           11.7.64  0                         nvidia/label/cuda-11.7.0/win-64      46MB
  + cuda-nvdisasm                       11.7.50  0                         nvidia/label/cuda-11.7.0/win-64      33MB
  + cuda-nvml-dev                       11.7.50  0                         nvidia/label/cuda-11.7.0/win-64      87kB
  + cuda-nvprof                         11.7.50  0                         nvidia/label/cuda-11.7.0/win-64       2MB
  + cuda-nvprune                        11.7.50  0                         nvidia/label/cuda-11.7.0/win-64     155kB
  + cuda-nvrtc                          11.7.50  0                         nvidia/label/cuda-11.7.0/win-64      75MB
  + cuda-nvrtc-dev                      11.7.50  0                         nvidia/label/cuda-11.7.0/win-64      15MB
  + cuda-nvtx                           11.7.50  0                         nvidia/label/cuda-11.7.0/win-64      44kB
  + cuda-nvvp                           11.7.50  0                         nvidia/label/cuda-11.7.0/win-64     119MB
  + cuda-runtime                         11.7.0  0                         nvidia/label/cuda-11.7.0/win-64       1kB
  + cuda-sanitizer-api                  11.7.50  0                         nvidia/label/cuda-11.7.0/win-64      13MB
  + cuda-toolkit                         11.7.0  0                         nvidia/label/cuda-11.7.0/win-64       1kB
  + cuda-tools                           11.7.0  0                         nvidia/label/cuda-11.7.0/win-64       1kB
  + cuda-visual-tools                    11.7.0  0                         nvidia/label/cuda-11.7.0/win-64       1kB
  + filelock                             3.11.0  pyhd8ed1ab_0              conda-forge/noarch                   14kB
  + freetype                             2.12.1  h546665d_1                conda-forge/win-64                  497kB
  + git                                  2.40.0  h57928b3_1                conda-forge/win-64                   98MB
  + idna                                    3.4  pyhd8ed1ab_0              conda-forge/noarch                   57kB
  + intel-openmp                       2023.0.0  h57928b3_25922            conda-forge/win-64                    2MB
  + jinja2                                3.1.2  pyhd8ed1ab_1              conda-forge/noarch                  101kB
  + jpeg                                     9e  hcfcfb64_3                conda-forge/win-64                  289kB
  + lcms2                                  2.15  ha5c8aab_0                conda-forge/win-64                  498kB
  + lerc                                  4.0.0  h63175ca_0                conda-forge/win-64                  194kB
  + libblas                               3.9.0  16_win64_mkl              conda-forge/win-64                    6MB
  + libcblas                              3.9.0  16_win64_mkl              conda-forge/win-64                    6MB
  + libcublas                        11.10.1.25  0                         nvidia/label/cuda-11.7.0/win-64      24kB
  + libcublas-dev                    11.10.1.25  0                         nvidia/label/cuda-11.7.0/win-64     300MB
  + libcufft                          10.7.2.50  0                         nvidia/label/cuda-11.7.0/win-64       6kB
  + libcufft-dev                      10.7.2.50  0                         nvidia/label/cuda-11.7.0/win-64     262MB
  + libcurand                        10.2.10.50  0                         nvidia/label/cuda-11.7.0/win-64       3kB
  + libcurand-dev                    10.2.10.50  0                         nvidia/label/cuda-11.7.0/win-64      52MB
  + libcusolver                       11.3.5.50  0                         nvidia/label/cuda-11.7.0/win-64      30kB
  + libcusolver-dev                   11.3.5.50  0                         nvidia/label/cuda-11.7.0/win-64      91MB
  + libcusparse                       11.7.3.50  0                         nvidia/label/cuda-11.7.0/win-64      14kB
  + libcusparse-dev                   11.7.3.50  0                         nvidia/label/cuda-11.7.0/win-64     155MB
  + libdeflate                             1.17  hcfcfb64_0                conda-forge/win-64                  152kB
  + libffi                                3.4.2  h8ffe710_5                conda-forge/win-64                   42kB
  + libhwloc                              2.9.0  h51c2c0f_0                conda-forge/win-64                    3MB
  + libiconv                               1.17  h8ffe710_0                conda-forge/win-64                  715kB
  + liblapack                             3.9.0  16_win64_mkl              conda-forge/win-64                    6MB
  + liblapacke                            3.9.0  16_win64_mkl              conda-forge/win-64                    6MB
  + libnpp                            11.7.3.21  0                         nvidia/label/cuda-11.7.0/win-64     293kB
  + libnpp-dev                        11.7.3.21  0                         nvidia/label/cuda-11.7.0/win-64     120MB
  + libnvjpeg                         11.7.2.34  0                         nvidia/label/cuda-11.7.0/win-64       4kB
  + libnvjpeg-dev                     11.7.2.34  0                         nvidia/label/cuda-11.7.0/win-64       2MB
  + libpng                               1.6.39  h19919ed_0                conda-forge/win-64                  344kB
  + libsqlite                            3.40.0  hcfcfb64_0                conda-forge/win-64                  670kB
  + libtiff                               4.5.0  hf8721a0_2                conda-forge/win-64                    1MB
  + libuv                                1.44.2  h8ffe710_0                conda-forge/win-64                  370kB
  + libwebp-base                          1.3.0  hcfcfb64_0                conda-forge/win-64                  268kB
  + libxcb                                 1.13  hcd874cb_1004             conda-forge/win-64                    1MB
  + libxml2                              2.10.3  hc3477c8_6                conda-forge/win-64                    2MB
  + libzlib                              1.2.13  hcfcfb64_4                conda-forge/win-64                   71kB
  + m2w64-gcc-libgfortran                 5.3.0  6                         conda-forge/win-64                  351kB
  + m2w64-gcc-libs                        5.3.0  7                         conda-forge/win-64                  532kB
  + m2w64-gcc-libs-core                   5.3.0  7                         conda-forge/win-64                  219kB
  + m2w64-gmp                             6.1.0  2                         conda-forge/win-64                  744kB
  + m2w64-libwinpthread-git  5.0.0.4634.697f757  2                         conda-forge/win-64                   32kB
  + markupsafe                            2.1.2  py310h8d17308_0           conda-forge/win-64                   26kB
  + mkl                                2022.1.0  h6a75c08_874              conda-forge/win-64                  192MB
  + mkl-devel                          2022.1.0  h57928b3_875              conda-forge/win-64                    7MB
  + mkl-include                        2022.1.0  h6a75c08_874              conda-forge/win-64                  779kB
  + mpmath                                1.3.0  pyhd8ed1ab_0              conda-forge/noarch                  438kB
  + msys2-conda-epoch                  20160418  1                         conda-forge/win-64                    3kB
  + networkx                                3.1  pyhd8ed1ab_0              conda-forge/noarch                    1MB
  + ninja                                1.11.1  h91493d7_0                conda-forge/win-64                  279kB
  + nsight-compute                  2022.2.0.13  0                         nvidia/label/cuda-11.7.0/win-64     352MB
  + numpy                                1.24.2  py310hd02465a_0           conda-forge/win-64                    6MB
  + openjpeg                              2.5.0  ha2aaf27_2                conda-forge/win-64                  237kB
  + openssl                               3.1.0  hcfcfb64_0                conda-forge/win-64                    7MB
  + pillow                                9.4.0  py310hdbb7713_1           conda-forge/win-64                   46MB
  + pip                                  23.0.1  pyhd8ed1ab_0              conda-forge/noarch                    1MB
  + pthread-stubs                           0.4  hcd874cb_1001             conda-forge/win-64                    6kB
  + pthreads-win32                        2.9.1  hfa6e2cd_3                conda-forge/win-64                  144kB
  + pycparser                              2.21  pyhd8ed1ab_0              conda-forge/noarch                  103kB
  + pyopenssl                            23.1.1  pyhd8ed1ab_0              conda-forge/noarch                  128kB
  + pysocks                               1.7.1  pyh0701188_6              conda-forge/noarch                   19kB
  + python                               3.10.9  h4de0772_0_cpython        conda-forge/win-64                   16MB
  + python_abi                             3.10  3_cp310                   conda-forge/win-64                    6kB
  + pytorch                               2.0.0  py3.10_cuda11.7_cudnn8_0  pytorch/win-64                        1GB
  + pytorch-cuda                           11.7  h16d0643_3                pytorch/win-64                        7kB
  + pytorch-mutex                           1.0  cuda                      pytorch/noarch                        3kB
  + requests                             2.28.2  pyhd8ed1ab_1              conda-forge/noarch                   57kB
  + setuptools                           67.6.1  pyhd8ed1ab_0              conda-forge/noarch                  580kB
  + sympy                                1.11.1  pyh04b8f61_3              conda-forge/noarch                    5MB
  + tbb                                2021.8.0  h91493d7_0                conda-forge/win-64                  154kB
  + tk                                   8.6.12  h8ffe710_0                conda-forge/win-64                    4MB
  + torchaudio                            2.0.0  py310_cu117               pytorch/win-64                        6MB
  + torchvision                          0.15.0  py310_cu117               pytorch/win-64                        8MB
  + typing_extensions                     4.5.0  pyha770c72_0              conda-forge/noarch                   31kB
  + tzdata                                2023c  h71feb2d_0                conda-forge/noarch                  118kB
  + ucrt                           10.0.22621.0  h57928b3_0                conda-forge/win-64                    1MB
  + urllib3                             1.26.15  pyhd8ed1ab_0              conda-forge/noarch                  113kB
  + vc                                     14.3  hb6edc58_10               conda-forge/win-64                   16kB
  + vs2015_runtime                  14.34.31931  h4c5c07a_10               conda-forge/win-64                  725kB
  + wheel                                0.40.0  pyhd8ed1ab_0              conda-forge/noarch                   56kB
  + win_inet_pton                         1.1.0  pyhd8ed1ab_6              conda-forge/noarch                    8kB
  + xorg-libxau                           1.0.9  hcd874cb_0                conda-forge/win-64                   58kB
  + xorg-libxdmcp                         1.1.3  hcd874cb_0                conda-forge/win-64                   68kB
  + xz                                    5.2.6  h8d14728_0                conda-forge/win-64                  218kB
  + zstd                                  1.5.2  h12be248_6                conda-forge/win-64                  288kB

  Summary:

  Install: 123 packages

  Total download: 3GB

----------------------------------------------------------------------------------------------------------------------



Transaction starting
msys2-conda-epoch                                    3.2kB @  46.2kB/s  0.1s
pytorch-mutex                                        2.9kB @  36.4kB/s  0.1s
ca-certificates                                    146.6kB @   1.3MB/s  0.1s
lerc                                               194.4kB @ 861.9kB/s  0.1s
pthreads-win32                                     144.3kB @ 637.5kB/s  0.1s
bzip2                                              152.2kB @ 406.0kB/s  0.1s
m2w64-gmp                                          743.5kB @   1.5MB/s  0.4s
ucrt                                                 1.3MB @   2.4MB/s  0.5s
libpng                                             343.9kB @ 480.0kB/s  0.2s
m2w64-gcc-libgfortran                              350.7kB @ 473.0kB/s  0.2s
xorg-libxau                                         58.0kB @  70.7kB/s  0.1s
openjpeg                                           237.1kB @ 232.6kB/s  0.2s
libtiff                                              1.2MB @ 926.6kB/s  0.5s
tk                                                   3.7MB @   1.9MB/s  1.6s
blas-devel                                          13.5kB @   6.8kB/s  0.0s
openssl                                              7.5MB @   2.2MB/s  3.2s
liblapack                                            5.9MB @   1.7MB/s  2.3s
critical libmamba Download error (28) Timeout was reached [https://binstar-cio-packages-prod.s3.amazonaws.com/62eaaa07c]    SSL/TLS connection timeout

Conda environment creation failed.
Press any key to continue . . .
```

### System Info

```shell
windows 11

nvidia rtx 4090
```

**Comment by Loufe** [comment]
Just to check, you have run this multiple times and it gets stuck there each time? Seems like the download just got cut off (internet connection dropped, possibly?)

**Comment by dronelove** [comment]
had same problem but installed using a newer version of the installer found below and it worked. the issue is the installer download link on the main repo goes to an older version
https://github.com/oobabooga/one-click-installers

**Comment by AbslanX** [comment]
cloned the latest repo at one-click-installers and ran the install.bat a few times ending with this error : 

critical libmamba Download error (28) Timeout was reached [https://binstar-cio-packages-prod.s3.amazonaws.com/60ef38d5c]
    Resolving timed out after 10000 milliseconds

**Comment by AbslanX** [comment]
> Just to check, you have run this multiple times and it gets stuck there each time? Seems like the download just got cut off (internet connection dropped, possibly?)

yes, I ran the installer multiple times.

**Comment by UserSpy** [comment]
I had a similar problem, and I fixed it. I downloaded from the link dronelove gave and it got further but still errored out and whenever I ran it again it would just say the environment was empty. So I went into installer_files and deleted the "env" folder, and ran it again and it picked up right where it left off before. And finisehd installing

**Comment by jllllll** [comment]
Try this: https://github.com/oobabooga/text-generation-webui/issues/908#issuecomment-1501005462

**Comment by AbslanX** [comment]
> Try this: [#908 (comment)](https://github.com/oobabooga/text-generation-webui/issues/908#issuecomment-1501005462)

where should I make this change?

**Comment by jllllll** [comment]
@AbslanX 

Line 23 of `install.bat`

**Comment by AbslanX** [comment]
I'm still seeing the same error even with the change to the install.bat 

`critical libmamba Download error (28) Timeout was reached [https://binstar-cio-packages-prod.s3.amazonaws.com/60ef38a7f]
    Resolving timed out after 10000 milliseconds
`

**Comment by jllllll** [comment]
I honestly don't know then. It must be an issue with your network connecting to their server. Maybe a vpn could help. Other than that, I don't know.

**Comment by AbslanX** [comment]
> I honestly don't know then. It must be an issue with your network connecting to their server. Maybe a vpn could help. Other than that, I don't know.

Thank you for mentioning the VPN.  It reminded me that I had NordVPN active.  I disabled it and ran the installer.  I still hit the error, but I then deleted the env folder and ran the installer again.  This seemed to work and the installation was successful.  

Closing this issue.  Thank you.

**Comment by jllllll** [comment]
Yeah, it's important to note that repo info and package urls are cached for re-use.
